# Travis CI configuration file.
# https://docs.travis-ci.com/user/getting-started/

# https://docs.travis-ci.com/user/multi-os/
os:
  - linux

# https://docs.travis-ci.com/user/trusty-ci-environment/
# Use the new Debian 14 containers.
dist: trusty
sudo: false

# https://docs.travis-ci.com/user/languages/javascript-with-nodejs/#Specifying-Node.js-versions
# If you need to install a second programming language in your current
# build environment, for example installing a more recent version of
# Ruby than the default version present in all build environments you
# can do so in the `before_install` stage of the build.
language: node_js
node_js:
  - "node" 

# https://docs.travis-ci.com/user/customizing-the-build/#Git-Clone-Depth
git:
  # Limit the clone depth; default is 50.
  depth: 3

# https://docs.travis-ci.com/user/environment-variables/
env:
  global:
    - SCRIPT="scripts/travis.sh"

# https://docs.travis-ci.com/user/notifications/#Configuring-email-notifications
notifications:
  email:
    on_success: always # default: change
    on_failure: always # default: always

# -----------------------------------------------------------------------------

# before_install:
#  - ...

# Skip the install step.
# install: true

# before_script:
#  - ...

script:
  - npm test
  
# Unused, kept for just in case.

# after_success:
#  - bash "${SCRIPT}" after_success

# after_failure:
#   - bash "${SCRIPT}" after_failure
  
# after_script:
#   - bash "${SCRIPT}" after_script

# -----------------------------------------------------------------------------
