# Travis CI configuration file.
# https://docs.travis-ci.com/user/getting-started/

# https://docs.travis-ci.com/user/multi-os/
os:
  - linux

# https://docs.travis-ci.com/user/trusty-ci-environment/
# dist: trusty # 14
# dist: xenial # 16
dist: bionic # 18
sudo: false

# https://docs.travis-ci.com/user/languages/javascript-with-nodejs/#Specifying-Node.js-versions
# If you need to install a second programming language in your current
# build environment, for example installing a more recent version of
# Ruby than the default version present in all build environments you
# can do so in the `before_install` stage of the build.
language: node_js
node_js:
  - "12" 
  - "10" 
  - "8"

# https://docs.travis-ci.com/user/customizing-the-build/#Git-Clone-Depth
git:
  # Limit the clone depth; default is 50.
  depth: 3

# https://docs.travis-ci.com/user/environment-variables/
# env:
#   global:
#     - SCRIPT="scripts/travis.sh"

# https://docs.travis-ci.com/user/notifications/#Configuring-email-notifications
notifications:
  email:
    on_success: always # default: change
    on_failure: always # default: always

# -----------------------------------------------------------------------------

# before_install:
#  - ...

# Skip the install step.
# install: true

# before_script:
#  - ...

script:
  - npm run test
  
# -----------------------------------------------------------------------------
